### ISSUE TITLE
cpu100%运行

### ISSUE THREAD

**Issue by creastall** [cookeem/chatgpt-service#2]
回答聊天结束前（回答过程中），有概率出现服务器cpu突然100%运行，貌似进入了死循环，只能重启服务器。
以下是部分使用top命令查看的
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                        
  858 1000      20   0  720736  13472   7680 R  99.3   2.7   7:48.41 chatgpt-service                                                                
  464 root      20   0 1319484  26356  18044 S   0.3   5.3   0:15.95 x-ui                                                                           
 1902 root      20   0       0      0      0 I   0.3   0.0   0:00.50 kworker/0:1-events_power_efficient                                             
 1917 root      20   0   11256   3704   3156 R   0.3   0.7   0:00.31 top                                                                            
    1 root      20   0   21932  10068   7904 S   0.0   2.0   0:02.39 systemd                                                                        
    2 root      20   0       0      0      0 S   0.0   0.0   0:00.01 kthreadd

**Comment by cookeem** [comment]
会不会是访问chatgpt的网络不稳定引起卡死？我这里的新加坡服务器是很稳定的

**Comment by creastall** [comment]
我的是美国纽约布法罗的vps，即使网络不稳定也应该延迟或断开网络，不应该出现高cpu的状态吧

**Comment by cookeem** [comment]
我检查一下看看什么问题

**Comment by cookeem** [comment]
死循环经常是因为chatGPT服务端返回不了信息，导致一直循环，我添加了会话的超时设置，超时自动结束会话

**Comment by cookeem** [comment]
找到原因了，原来是官方的GPT-3的SDK有问题，官方升级了一个版本修复了接收stream的问题了。我重新升级了，你再测试一下？

**Comment by creastall** [comment]
好的，谢谢
