### ISSUE TITLE
执行chatgpt-service后，输入问题无响应，100%出现。

### ISSUE THREAD

**Issue by creastall** [cookeem/chatgpt-service#3]
安装你的如下步骤执行后，不管是使用wscat链接还是外部websocket链接都是可以链接，但是无法发送数据。出现输入问题无响应的情况，而且是100%出现。（测试服务器：美国和新加坡），另外，还需要安装Nginx吗？

go mod tidy
go build
./chatgpt-service
npm install -g wscat
wscat --connect ws://localhost:9000/api/ws/chat

**Comment by EdenSpark** [comment]
遇到了一样的问题，偶尔可以成功一次，但不能连续对话

**Comment by cookeem** [comment]
@creastall 应该是能够收到request，但是response只有chatGPT有回应才会有反应。收到request之后，服务端会返回一个收到request的响应的，你收到没有？

我更新了一个版本，升级了sdk，你看看是否正常？

**Comment by creastall** [comment]
// read in a message
		api.Logger.LogInfo(fmt.Sprintf("ReadMessage 1111"))
		messageType, bs, err := conn.ReadMessage()
		api.Logger.LogInfo(fmt.Sprintf("ReadMessage 2222"))
我在这里增加了两个打印，发现websocket open后，先打印“ReadMessage 1111”，然后等待接受消息，客户端发送消息，有大概率会收不到消息，也就是说不会打印：“ReadMessage 2222”

**Comment by cookeem** [comment]
你打印一下isClosed，看看是不是isClosed被设置为true导致连接关闭了？

**Comment by creastall** [comment]
测试了，不是isClosed被设置为了true，按照上面逻辑，客户端发送消息后，主动断开，服务器端打印的消息如下：
INFO[2023-02-15 11:27:17.964] websocket connection open                    
INFO[2023-02-15 11:27:17.964] ReadMessage 1111                             
INFO[2023-02-15 11:27:21.810] # websocket connection closed                
INFO[2023-02-15 11:27:21.810] conn isClosed 22                             
INFO[2023-02-15 11:27:21.810] ReadMessage 2222                             
ERRO[2023-02-15 11:27:21.810] read message error: read tcp 172.17.54.5:9000->125.69.12.212:24645: use of closed network connection 
INFO[2023-02-15 11:27:21.810] conn isClosed 11                             
以下是打印的位置：

var isClosed bool
chClose := make(chan int)
chIsCloseSet := make(chan int)
defer func() {
api.Logger.LogInfo(fmt.Sprintf("conn isClosed 11"))
conn.Close()
}()
go api.wsCheckConnectStatus(conn, chClose)
go api.wsPingMsg(conn, chClose, chIsCloseSet)
go func() {
for {
	select {
	case <-chIsCloseSet:
		isClosed = true
		api.Logger.LogInfo(fmt.Sprintf("conn isClosed 22"))
		return
	}
}
}()

api.Logger.LogInfo(fmt.Sprintf("websocket connection open"))
cli := gogpt.NewClient(api.Config.AppKey)

var latestRequestTime time.Time
for {
if isClosed {
	api.Logger.LogInfo(fmt.Sprintf("conn isClosed"))
	return
}
// read in a message
api.Logger.LogInfo(fmt.Sprintf("ReadMessage 1111"))
messageType, bs, err := conn.ReadMessage()
api.Logger.LogInfo(fmt.Sprintf("ReadMessage 2222"))

断开链接了，居然还在打印接受websocket的消息

**Comment by cookeem** [comment]
呃，你这里这么奇怪？你用docker-compose来部署那个服务看看？是不是你的电脑设置了代理什么的？

**Comment by creastall** [comment]
关闭了代理，docker-compose应该没有问题

**Comment by cookeem** [comment]
你删除掉原先的docker镜像，重新拉取代码，docker-compose up -d再看看？

**Comment by varluffy** [comment]
同样的问题 偶尔才会成功一次 感觉是 socket那里接收的问题 不像是代理的问题

**Comment by cookeem** [comment]
还没有找到服务端不接收的原因在哪里，不过我这边部署的服务貌似没有出现这个问题

**Comment by varluffy** [comment]
刚测试了一下 
go api.wsCheckConnectStatus(conn, chClose) 
 这行代码注释掉就可以了 问题应该是出现在这里

**Comment by cookeem** [comment]
@varluffy 确实这个地方有问题，把发送的消息读取了，没做任何处理导致。感谢感谢，我回去修复一下bug

**Comment by cookeem** [comment]
@varluffy @creastall @EdenSpark   确实代码有问题，有两处地方读取websocket的消息，已经修复。
