### ISSUE TITLE
连续提问chatgpt-service不响应

### ISSUE THREAD

**Issue by yingjianan** [cookeem/chatgpt-service#4]
1，服务器部署在海外，用wscat或者chatgpt-stream出现一致的问题。
2，一般提问3-5次之后出现不响应，chatgpt-service 日志没用发现断开的情况，但是没用client发的消息日志。

**Comment by yingjianan** [comment]
排除网络问题，wscat 直接在海外服务器上连chatgpt-service出现情况是一致的，我使用docker-compose 部署的

**Comment by panw3i** [comment]
代码问题

**Comment by cookeem** [comment]
@yingjianan @panw3i 确实代码有问题，有两处地方读取websocket的消息，已经修复。
