### ISSUE TITLE
更新GPT3.5后，官方API接口需要翻墙访问，导致你的项目无法正常运行，有什么解决办法吗？之前是不需要翻墙的

### ISSUE THREAD

**Issue by luoqianyi** [cookeem/chatgpt-service#5]
https://api.openai.com/，这个我ping了，IP不可以在国内访问到

**Comment by cookeem** [comment]
这个项目需要VPN或者海外服务器

**Comment by cookeem** [comment]
之前不用翻墙？这个之前是前到什么时候啊？

**Comment by luoqianyi** [comment]
> 之前不用翻墙？这个之前是前到什么时候啊？

今天下午使用时发现不可以用了

**Comment by luoqianyi** [comment]
> 这个项目需要VPN或者海外服务器

我在尝试使用给请求加国外代理的方式来获取，很多gpt3.5 api的项目似乎都是使用了这种方式

**Comment by cookeem** [comment]
openai国家去年就已经封了啊

**Comment by luoqianyi** [comment]
> openai国家去年就已经封了啊

是的，但是我到今天出了3.5才不能翻墙用，害。。。

**Comment by luoqianyi** [comment]
已经解决了，我给我的服务器加全局代理了😅，不过请问可以将项目改成对话式的吗？只能一问一答太有局限了，如果要改的话，可能代码动的地方比较多了😅

**Comment by xgo-m** [comment]
> 

怎么解决的能教一下吗？

**Comment by cookeem** [comment]
> 已经解决了，我给我的服务器加全局代理了😅，不过请问可以将项目改成对话式的吗？只能一问一答太有局限了，如果要改的话，可能代码动的地方比较多了😅

现在就是对话方式啊，可以不等接口返回信息你继续问的
